### PR TITLE
Add San Leandro, CA

### LINKED ISSUE #819: Please add San Leandro CA PD
**Email addresses**: pcutter@sanleandro.org , pballew@sanleandro.org , dcox@sanleandro.org , ehernandez@sanleandro.org , vaguilar@sanleandro.org , blee@sanleandro.org , clopez@sanleandro.org

**Subject line**: SLPD Budget Reallocation 2020

**Message:**

Dear Mayor Cutter and City Council Members, 

My name is [YOUR NAME] and I am a San Leandro (resident or business owner) writing to urge you to defund SLPD.

SLPD takes an enormous share of the city’s general fund, and that percentage has risen exponentially for the last two decades, taking away desperately needed resources from essential city programs and services. The City of San Leandro transferred $20 million to the SLPD headquarter fund in 2018-2019; money that could be used much more beneficially if inserted directly into the community. The investment in policing has not made us safer – SLPD remains an embarrassment to the city and a lethal threat to San Leandro’s Black and Brown communities, while increased police spending shows no correlation to decreasing crime levels. With current finances so tight, it is clear that we must defund the police.

As San Leandro residents, we therefore demand that you take immediate action to ensure the following:

- Reduce SLPD’s allocation from the General Fund by 50% 
- Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
- Reallocate money from SLPD into housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
- San Leandro can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund SLPD.

Thank you,

[YOUR NAME]

### PR DESCRIPTION
**Pull request by swallan**
Closes #819

### CODE REVIEW

**Comment by jamiecatton** [comment]
I just got an email about this, is there anything I need to do?

**Comment by swallan** [comment]
@jamiecatton,

If you would like to add anything to this message, you can suggest it. Otherwise, it will be added and ready to send soon once approved.

**Comment by jamiecatton** [comment]
Okay, great. I spent a lot of time on this, so please feel free to reach out with suggestions if it needs work. I'll be sharing this with my apartment complex once it's live on the page

**Comment by swallan** [comment]
@jamiecatton We can definitely add some of the stuff you included in your email to this one about the budgets, right after we clear up this issue that closed the PRs.

**Comment by jamiecatton** [comment]
@swallan awesome. After figuring out how to navigate the branch system in GitHub, I was able to provide my feedback on the email in the original post. I merged the two emails in hopes to keep the sentiment of the original and the percentages and numbers from mine.

**Comment by swallan** [comment]
@jamiecatton Great. We'll get that added to the site with a PR as soon as we can fix the issue! Github can be very complicated even for the pros!

**Comment by jamiecatton** [comment]
@swallan thank you for your efforts!

**Comment by swallan** [comment]
@jamiecatton Of course! Several of my friends live in San Leandro. Just so you know, we have to make all these emails relatively general, and not pointing towards funding specific issues, so it might be lightly edited one last time.

**Comment by jamiecatton** [comment]
@swallan of course, I understand!

**Pull request closed without merging**
