### PR TITLE
Create kansascityMO.md

### LINKED ISSUE #490: Kansas City, Missouri
To: MayorQ@kcmo.org, heather.hall@kcmo.org, Kevin.ONeill@kcmo.org, Teresa.Loar@kcmo.org, amy.justis@kcmo.org, Brandon.Ellington@kcmo.org, Melissa.Robinson@kcmo.org, katheryn.shields@kcmo.org, Eric.Bunch@kcmo.org, Keema.McCoy@kcmo.org, Angela.Pearson@kcmo.org, Katrina.Foster@kcmo.org, fred.wickham@kcmo.org

Subject: Defund the Kansas City Police Department

Message (Don't forget to replace the [x]'s with your information!) 

Hello, 

My name is [NAME] and I am a resident of Kansas City’s [YOUR DISTRICT]. I am writing to ask you to reallocate funds away from the KCPD and toward public resources such as healthcare services, housing, and education. 

The city’s recently approved FY2020-21 budget promises ~$270 million to police alone, which is ~$50 million more than the entire budget for Neighborhoods, Housing, and Healthy Communities in this fiscal year. This year’s policing budget brings a $10.7 million increase from the previous year’s budget, an increase enabling ten new police officer positions as well as wage increases and pensions for existing officers. 

As the city’s policing budget increases, direct investment in our communities continues to be overlooked. No part of the budget was reserved for the fulfillment of Office of Tenant Advocate, a mere $1.2 million dollar budget proposal from the KC Tenants group to Mayor Lucas. This proposal, made to fulfill the Tenants Bill of Rights passed by the mayor and city council in December 2019, was seemingly ignored in the city’s budget. This is but one example of the way that police funding interferes with and blocks the allocation of funds back into our communities, as a result perpetuating racial and economic inequality in Kansas City. 

On June 4th, 2020, Mayor Lucas announced “significant” police oversight measures. While these measures indicate that the mayor and city council are open to hearing the demands of the people and pursuing police accountability, the measures themselves do not address the issue of police department overfunding in the city’s FY2020-21 budget.  

There is little evidence that more policing and increased wages for police officers correlates to safer communities. Investment in the police does not equal an investment in communities. To truly hold police accountable and uplift civilians, I would like to see an immediate reconsideration and revision of police funding in our city so that we might begin to adequately invest in our communities. 

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

### PR DESCRIPTION
**Pull request by Ceshion**
closes #490

### CODE REVIEW

**Comment by Ceshion** [comment]
addresses #490

**Comment by swallan** [comment]
closes #490

**Comment by milesalex** [comment]
closes #490

**Comment by Ceshion** [comment]
@milesalex what error do you see? This is building for me, and I can load the email locally.

**Comment by skullface** [comment]
Updated content in #490

**Pull request merged**
