### PR TITLE
Add Jacksonville, FL

### LINKED ISSUE #504: Defund Jacksonville Sheriff's Office Jacksonville FL
MayorLennyCurry@coj.net
JoyceMorgan@coj.net
Ferraro@coj.net
ABowman@coj.net
SWilson@coj.net
LCumber@coj.net 
MBoylan@coj.net  
RGaffney@coj.net
JPittman@coj.net 
GarrettD@coj.net
BPJackson@coj.net 
DBecton@coj.net
RandyWhite@coj.net
RDiamond@coj.net 
 RDeFoor@coj.net 
TFreeman@coj.net 
GerrieF@coj.net 
RSalem@coj.net 
THazouri@coj.net
MCarlucci@coj.net 
SNewby@coj.net

Hi, my name is [NAME] and I am a resident of [YOUR DISTRICT]. 

I am a citizen who is disturbed by the injustices and brutality carried out by police forces across the country, and particularly in the Jacksonville Sheriff’s Office. 

Racist police violence doesn’t just happen in other cities - it happens here in Jacksonville too. Our community has a long history of racist policy in housing and school segregation. Black citizens have been subjected to centuries of economic and social exclusion in Jacksonville. The current protests reflect concerned members of society taking direct, collective action to demand an end to the abuse and violence directed against Black people. These issues must become financial priorities so we can heal from our history. We want real change to be made to the way our city allocates its resources.

I urge you to pressure the Mayor to redirect money towards an ethical and equal reallocation of the City of Jacksonville’s expense budget, effective at the beginning of FY21. Commit to our city’s Black and Brown communities to combat an over-investment in their criminalization, surveillance, and discrimination. Now especially, the City Council can take a stand for racial justice by significantly defunding policing and investing in Black and Brown communities. Provide relief to those in our community that are marginalized and victimized by the structural racism and inequity that Jacksonville was built upon, and that JSO is complicit in enforcing. Public tensions are rising and public opinion is dwindling in regard to the City’s inappropriate over-policed response to subsequent protests of police brutality and racism.

Deprioritize JSO’s overinflated budget and meaningfully reallocate funds towards the following social services: Community Development, Affordable Housing Programs, Eviction Diversions, COVID Relief and Healthcare, Substance Abuse Treatment Services, Education, Childcare, Transportation, targeted support for marginalized communities and communities of color, Jobs, and Parks & Recreation. All of these sectors will facilitate the dismantling of racial and class inequality and will support racial and social justice, which will have both a short and long-term positive impact on our residents and their futures. This action will reflect the decades of research showing that social programs, education, and a living wage are far more successful at promoting the safety of a city than policing or prisons. We are overdue for change. Ending police brutality should be a budget priority. Justice should be a budget priority. Over policed communities are not safe communities. Thriving communities are safe communities, and communities thrive when they are well-resourced. We deserve a budget that divests from policing and jails and uses that money to invest in our communities. People are marching in the streets because they know that these actions will result in a healthier, more just society.  I implore you to please listen to the needs of your constituents and take immediate action to address their concerns.

JSO has been a waste of our resources. Last year, the JSO budget was $358,517,260, ($982,239.06 per day) almost all of which comes from taxes. This means the JSO budget was the single largest expenditure; higher than Fire and Rescue, Public Works, Parks and Recreation, Libraries, Neighborhoods, Planning and Development, Intra-Governmental Services, Finance, Special Services, Economic Development Office, Mayor’s Office, and our City Council budget combined. This isn’t how we create public safety. True public safety requires fully-funded and community-controlled resources, not more police and jails.

JSO is overfunded and holds responsibility over community issues that they are fundamentally unable to address. We have seen mounting evidence that police departments are ineffective institutions that marginalize minority communities and put citizens at risk of injury and death. Our city needs EMTs, social workers, and other social service providers to respond to the majority of current police business, including health and wellness checks, domestic/sexual violence situations, and basic bureaucratic documentation around break-ins, vandalism, wrecks, etc. It is morally reprehensible have armed police officers respond to these emergencies. More often than not, when police are dispensed, rather than more qualified medical, psychiatric, and social work professionals, the effect is to bring violence where none previously existed.

JSO offers “unlimited overtime pay for all” through Operation Safe and Sound, which, more often than not, is paid out to officers responsible for harassing the unhoused, and Black, Indigenous, people of color. Jacksonville’s needs must be addressed by the provision of care, and not the threat of violence. 

Crime is not random. Crime usually happens when someone has been unable to meet their basic needs through other means. So, to really “fight crime,” we don’t need more police officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

We don’t need a militarized police force. Divest from offensive weapons. Offensive weapons are known to escalate violence, especially when deployed in situations where none existed before. Almost all the current litany of Black men and women dead from police violence were non-violent, unarmed people, for whom armed police became the site of death and brutality. If you want to “tackle crime”, dedicate yourselves fully to ending poverty– don’t give the police force another $358 million+ to spend on riot gear, grenades, and chemical weapons like tear gas (which is considered a war crime to use according to 1925 Geneva protocol) to use against your own city.

History has shown that police “reform” will not be enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city.
I also urge the City Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity. I ask abusive cops be fired and criminally charged. Ending the unfair and secretive internal JSO grievance review process would be a good first step in achieving this goal. Propose plans for ensuring the safety of Black and other marginalized people in our community from racial profiling by police and other security forces, and release the bodycam footage of Jamee Johnson’s murder.
Do not forget our poor communities and communities of color who are disproportionate targets of police violence. Our violent police department is, quite frankly, upholding policies and practices that allow white supremacy to take Black lives every single day. 
Justice will only be served when the police are reformed, and this will not be possible until we defund them.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year. Public opinion is with me. We can be a beacon for other cities to follow if only we have the courage to change. Now is a chance for Jacksonville to lead the country and show how demilitarization and defunding the police can create a safer city for all of us.

Mayor Curry, will you look out for me, and will you look out for us? Can I count on you to pass an alternative budget that puts a focus on social service programs? 

Have the moral clarity to create a budget focused on communities instead of investing in a racist and destructive institution. Defund JSO.

I am eager to see how you will address these issues, which I will fight for until they are meaningfully addressed. We the residents of Jacksonville will hold you accountable for swift and just action, Mayor Curry.

Thank you for your time, 
[NAME]
[ADDRESS]
[EMAIL]
[PHONE NUMBER]

### PR DESCRIPTION
**Pull request by dionlarson**
Closes #504.

### CODE REVIEW

**Comment by dionlarson** [comment]
The letter must be edited down if we want "send message" to work, this actually issues the following from Gmail:
image

**Comment by dionlarson** [comment]
After further exploring the issue, I suggest we publish as is.

**Comment by minicreative** [comment]
@averymcguirt Can you comment on length here? If you feel it's too long, can you suggest edits?

**Comment by bingbongle** [comment]
This one still needs work. Going to close this PR - let's just create a new one once it's ready.

Sorry for the confusion. I'll make sure editors are aligned here.

**Pull request closed without merging**
