### PR TITLE
Portland, OR: remove reformist reforms / add abolitionist

### LINKED ISSUE #495: Email template for Portland, OR has discrepancy
Hello!

The email template for Defunding PPB in Portland, OR says both that we have a problem with eliminating the funding for body cams, AND that we oppose body cams.

If you could please fix to say one or the other, that would make our emails more effective and clear—thank you!

Ally

### PR DESCRIPTION
**Pull request by swallan**
closes #495

### CODE REVIEW

**Comment by swallan** [comment]
Additional edits to come, per issue requester

**Comment by AlYan20** [comment]
Suggested template rewrite
------
I am a resident of [YOUR CITY].

In May, Mayor Ted Wheeler released his proposed budget for the City of Portland. This included a policing budget of $245,169,804, which is over $5 million more than budgeted last year—even amongst city-wide cuts to other departments due to Covid-19. The Portland Police Bureau (PPB), with Wheeler at its helm as Commissioner, has been mired in controversy over the last year with collusion with prominent white nationalist groups, shootings of Black people and people perceived to be in mental health crisis, data uncovered on their racist gang enforcement traffic stops, and the fact that a shameful 52% of people arrested are houseless.

I oppose any increases to the PPB budget. Mayor Wheeler's 2019-20 proposed budget was increased by an additional half million dollars before adoption, and even then the PPB has overspent the increased budget by 1.4 million to date. We anticipate that PPB will attempt a similar increase this year, pushing their budget even higher than the proposed $245 million, thus we stand even more firmly against this increase. 

Additionally and critically, Wheeler's budget ELIMINATES $1.8 million to fund the police body camera program. More money for policing but less money for police accountability is completely unacceptable.

The police budget increases regularly while other services are cut. I can see the ways in which policing continues to perpetuate violence against Black, brown, houseless people, and against people in mental health crisis. While Wheeler's proposal represents a slight decrease from the PPB proposal, the PPB is a department whose reach into Portland communities needs to be curtailed through reducing the budget, not by increasing it.

More money for policing but less money for police accountability is completely unacceptable at this moment in history. The city, the state, and country are all watching. And so am I. I call on the Mayor, the Commissioners, and all other City Council Members to use their powers to continue to reduce the budget and pledge to increase Police accountability and transparency. I promise that you will lose my support and my vote if you aren't willing to make a public and vocal stand to help defund the PPB and increase their accountability and transparency.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
------
Change log
**Note: Most of the text of the original letter has come from a 2019 article from Critical Resistance.org. The sentiments are correct, but the numbers are out of date.
With concern for the efficacy of these templates, please consider asking submitters to cite sources and fact check. Thank you for your work and for creating such a useful resource for action!**

1. The quoted budget is from the 2019/20 budget. We have updated the cited $236,991,195 to $245,169,804, which is the actual proposed total budget for the 2020-2021 fiscal year.
    1a. “over 10 million more than last year” This is incorrect, the actual (to date) spending of the PPB this year is 239.5 hundred million (with a proposed 2019-2020 budget of 238 hundred million). This is about 6 million more than last year. We have rephrased the line to say “Over 5 million”.

2. “We also continue to oppose the proposed funding in this year’s budget for body cameras which are not shown to reduce the occurrence of police violence but rather are used to surveil and criminalize community members.” has been removed because in directly contradicts an earlier line, and also it's wrong. Funding for the program has been cut this year.

3. “Wheeler's budget does have a few positive aspect…” This whole paragraph is relevant only to last year and has been cut.

Citations:
Proposed budget 2019/20 - https://www.portlandoregon.gov/cbo/article/731005
Approved budget change memo 2019/20 - https://www.portlandoregon.gov/cbo/article/735056
Adopted budget 2019/20 - https://www.portlandoregon.gov/cbo/article/738382
Proposed budget 2020/21 - https://www.portlandoregon.gov/cbo/article/760527
Original article cited in previous template from 2019 - http://criticalresistance.org/portland-demands-peoples-budget-over-policing/

**Comment by swallan** [comment]
Hm, I don't think the indentation of the text I added is right.

**Comment by milesalex** [comment]
lmk when this is ready to go!

**Comment by swallan** [comment]
@milesalex I believe it should be good now.

**Comment by TessMyers** [comment]
Is there anything blocking this PR that I could help with? PDX city budget is due in 2 days and the current letter is factually incorrect.

**Comment by swallan** [comment]
> Is there anything blocking this PR that I could help with? PDX city budget is due in 2 days and the current letter is factually incorrect.

@TessMyers 

file structure were changed, so a new PR will be opened.

**Pull request closed without merging**
