### PR TITLE
Fix Boulder email body

### PR DESCRIPTION
**Pull request by jessenestler**
Replaced approximate funding numbers with exact funding numbers, sourced
from Boulder's 2020 Budget Documentation. As a result, the logic of the
email's argument had to shift to a discussion of how budgets have grown
or shrunk since 2018, which was a strong funding year.

### CODE REVIEW

**Comment by shortcircuit3** [comment]
Does this fix an issue?

**Comment by jessenestler** [comment]
It fixes an issue with the funding numbers being reported.

Previously the email cited <$5,000,000 (which I could not corroborate from any sources) going to the city's HHS, but the figure from the most recent budget was $21,000,000.

**Comment by shortcircuit3** [comment]
Please the issue you are fixing by adding `closes #324234244` in the main comment. ALso issues  need to be tagged with the yellow tag before us creating PRs.

**Comment by jessenestler** [comment]
I’m sorry, new to collaborating on github. Are you saying I should have opened an issue first, labeled it yellow, then opened this PR? I just opened this PR without documenting an issue...

**Comment by bingbongle** [comment]
Closes: https://github.com/defund12/defund12.org/issues/749

**Pull request merged**
