### PR TITLE
Remove typo in Santa Cruz letter

### LINKED ISSUE #791: Typo in Santa Cruz pd (California) letter
Last line of form letter for Santa Cruz pd (CA) has an extra ‘our’
” if **our** you and our other city officials have the courage to step up.”

Keep up the good work!

### PR DESCRIPTION
**Pull request by jessenestler**
Closes #791

### CODE REVIEW

**Comment by jessenestler** [comment]
Fixes issue #791

**Comment by shortcircuit3** [comment]
Leave fixes comment in pr description. See: https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by jessenestler** [comment]
@shortcircuit3 done

**Comment by swallan** [comment]
Looks good.

**Pull request merged**
