### PR TITLE
Updating oakland wording

### PR DESCRIPTION
**Pull request by cjappl**
Hey all,

Heard from APTP (local organization who helped draft the original email) that they wanted point 3 removed, as it opened up some legal liability for them.

Submitting a request to delete that bullet point.

Thanks!

### CODE REVIEW

**Comment by swallan** [comment]
Are they linking to the email in some way that makes them responsible for it? I'm not opposed or for removing it, but what is their authority on for defund12 to have it in relation to their own legal (?) issue?

**Comment by cjappl** [comment]
I’m not entirely sure, here is the information i received:


“Could you pls make a quick fix to the defund 12 email? a close ally
advised us to drop the demand #3 about opd legal settlements. She said it
opened us up to unintended consequences. Would you mind deleting it when
you get a chance? “

If you want me to dig in to understand more, i can, but seeing as they’re
the authority on police violence in oakland I was going to take them at
their word.

Let me know what you think!

**Comment by bingbongle** [comment]
@swallan please feel free to reassign to me when/if it's ready for PR - or close it out if it's not an issue.

**Comment by swallan** [comment]
@cjappl I initially just thought was an interesting edit since Oakland has had to pay some large settlements on behalf of the police in recent years (police sex ring, all kinds of stuff), and have paid almost half a billion in police settlements in the last decade. 

I guess it possibly might open the movement up to criticism by citizens who have been wronged not ending up with restitution, but it is also possible that they have other reasons. Thinking about it more, I think that we can take them at their word, so we should approve this change. 

I was going to do a rewording of the letter soon to keep it out of the spam filters anyways.

**Comment by cjappl** [comment]
Awesome! Thanks for all you do. Appreciate it a lot.

**Pull request merged**
